FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY Producer.csproj .
RUN dotnet restore "Producer.csproj"
COPY . .
RUN dotnet publish "Producer.csproj" -c Release -o /publish
COPY getting-started.properties /publish/

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as final
WORKDIR /app
COPY --from=build /publish .

#ENTRYPOINT [ "dotnet", "Producer.dll", "getting-started.properties"]

#dotnet Producer.dll getting-started.properties

#docker run -it producer:1.2
#docker login

#docker build -t producer:1.2 .
#docker tag $(docker images --quiet producer) /producer:1.2
#docker push /producer:1.2
